---
- hosts: "web02"
  become: yes
  become_method: sudo
  gather_facts: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: install base packages
      apt:
        name:
          - vim
          - net-tools
          - python3 
        state: present

    - name: install nginx
      apt: 
        name:
          - nginx
        state: present